import { SpeedInsights } from "@vercel/speed-insights/next"
import ThemeProvider from "@/Utils/ThemeProvider.jsx";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header.jsx";
import Footer from "@/Components/Footer/Footer.jsx";
import Particles from "@/Components/Animations/Particles.jsx";

const montserrat = Montserrat({
   variable: "--font-montserrat",
});


export const metadata = {
   title: "KodersUp | Portfolio",
   description: "Generated by create next app",
   icons: {
      icon: "/icons/favicon.PNG",
      shortcut: "/icons/shortcut.ico",
      apple: "/icons/apple-touch-icon.PNG",
   }
};

export default function RootLayout({ children }) {
   return (
      <html lang="ru" className={montserrat.variable}>
         <body>
            <SpeedInsights/>
            <Header />
            <div style={{ width: '100%', height: '100%', position: 'absolute', zIndex: '-999' }}>
               <Particles
                  particleColors={['#0095ff', '#0095ff']}
                  particleCount={200}
                  particleSpread={10}
                  speed={0.1}
                  particleBaseSize={50}
                  moveParticlesOnHover={true}
                  alphaParticles={false}
                  disableRotation={false}
               />
            </div>

            <ThemeProvider>
               {children}
            </ThemeProvider>
         </body>
      </html>
   );
}
